'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class OE_Cotton_Purchase_Return
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Textile.OE_Cotton_Purchase_Return", GetType(OE_Cotton_Purchase_Return).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column1_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column10_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column10.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column11_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column11.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column12_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column12.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column13_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column13.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column14_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column14.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column15_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column15.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column16_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column16.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column17_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column17.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column18_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column18.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column2_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column2.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column3_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column3.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column4_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column4.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column5_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column5.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column6_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column6.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column7_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column7.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column8_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column8.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Column9_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column9.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn1_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn1.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn10_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn10.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn2_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn2.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn21_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn21.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn23_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn23.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn3_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn3.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn4_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn4.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn5_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn5.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn58_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn58.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn59_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn59.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn6_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn6.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn62_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn62.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn63_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn63.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn64_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn64.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property DataGridViewTextBoxColumn67_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("DataGridViewTextBoxColumn67.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=157,Y=56}.
    '''</summary>
    Friend Shared ReadOnly Property PrintDialog1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("PrintDialog1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=56}.
    '''</summary>
    Friend Shared ReadOnly Property PrintDocument1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("PrintDocument1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
End Class
